--1번 문제
--계정이름 SAMPLE 비밀번호 1234
--sqlplus sys as sysdba
--CREATE 유저네임 INDENTIFIED BY 비밀번호
--GRANT RESOURCE,CONNECT DBA TO 유저네임 
--RESOURCE : 테이블 생성 권한
--CONNET : DB 접속 권한 
--DBA : DB 관련된 모든 권한 
--2번 문제
SELECT EMP_NAME,EMP_NO,DEPT_CODE,SALARY,BONUS,EMAIL
FROM EMPLOYEE 
 
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6') AND
SALARY >= 3000000 AND
EMAIL LIKE'___#_%'ESCAPE'#' AND 
BONUS IS NOT NULL AND 
SUBSTR(EMP_NO,8,1)=1;

--3번 문제 
--3) 시나리오 상황
--ORA-01045: user EMP lacks CREATE SESSION privilege; logon denied

--Grant SESSION to 유저아이디;

--CREATE USER KH_ACADEMY IDENTIFIED BY KH123;
--GRANT CONNECT, RESOURCE TO KH123;

--권한에서 TO 비밀번호가 아니라 유저명 입력해야합니다.

--4번 문제 
-- 사용한 테이블 생성 정보 --
--CREATE TABLE DEPARTMENT(
--DEPTCODE NUMBER PRIMARY KEY,
--DEPTNAME NVARCHAR2(10) NOT NULL // VARCHAR2 오타수정
--);

CREATE TABLE EMPLOYEE(
EMPNO NUMBER PRIMARY KEY,
EMPNAME VARCHAR2(10) NOT NULL,
DEPTNO NUMBER REFERENCES DEPARTMENT(DEPTCODE)
);

-- 실행한 조인 쿼리 --
--SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME
--FROM EMPLOYEE
--JOIN DEPARTMENT USING(DEPTNO);
--//JOIN DEPARTMENT ON(DEPTNO=DEPTCODE)





